---
- name: Including --> user_accounts.yml
  include_vars: user_accounts.yml

- name: Creating a user accounts
  user:
    name: "{{ item.name }}"
    state: present
    uid: "{{ item.uid }}"
    password: "{{ item.passwd | password_hash('sha512') }}"
  loop: "{{ user_accounts }}"
  no_log: yes
  ignore_errors: true

- name: Including --> server.yml
  include_tasks: server.yml
  when: inventory_hostname in groups['nfs_server']

- name: Including --> client.yml
  include_tasks: client.yml
  when: inventory_hostname in groups['nfs_clients']

- name: Configuring --> selinux
  selinux:
    policy: targeted
    state: permissive
