---
- name: Installing a required packages
  yum:
    name: nfs-utils
    state: present
  when: inventory_hostname == item.dest_host 
  loop: "{{ nfs_mounts }}"
  
- name: Configuring a NFS-client
  mount:
    src: "{{ item.src }}"
    path: "{{ item.dest }}"
    state: "{{ item.state }}"
    opts: rw,sync,hard
    fstype: nfs
  when: inventory_hostname == item.dest_host 
  loop: "{{ nfs_mounts }}"

