---
- name: Installing a required packages
  yum:
    name: nfs-utils
    state: present

- name: makesure mount point already created
  file:
    path: "{{ item.dest }}"
    state: directory
  loop: "{{ nfs_mounts }}"

- name: Configuring a NFS-client
  mount:
    src: "{{ item.src }}"
    path: "{{ item.dest }}"
    state: "{{ item.state }}"
    opts: rw,sync,hard
    fstype: nfs
  loop: "{{ nfs_mounts }}"

