---
- name: INSTALLING A REQUIRED PACKAGES
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"
  
- name: STARTING A SERVICES
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - nfs-server
    - rpcbind
    - firewalld
  notify:
    - config firewall rules

- name: Creating a user accounts on the remote system

- name: EXPORTING NFS SHARE.....
  template:
    src: exports.j2
    dest: /etc/exports
  notify:
    - restart nfs-server

# - name: Ensure required entries are made to hosts file. # Notes 1232
  # lineinfile:
  # path: /etc/exports
  # state: present
  # line: "{{ item }}"
# with_items:
  # - '/export/volumes  *(rw,no_root_squash,no_subtree_check,insecure)' 

- name: CONFIG SELINUX
  selinux:
    policy: targeted
    state: permissive


